import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
import Footer  from '../components/Footer'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend, LineChart, Line } from 'recharts'

const appointmentData = [
  { month:'Mar', count:320 }, { month:'Apr', count:410 }, { month:'May', count:385 },
  { month:'Jun', count:490 }, { month:'Jul', count:560 }, { month:'Aug', count:612 },
]

const patientData = [
  { month:'Mar', new:45 }, { month:'Apr', new:62 }, { month:'May', new:58 },
  { month:'Jun', new:73 }, { month:'Jul', new:89 }, { month:'Aug', new:96 },
]

const conditionDist = [
  { name:'Hypertension', value:32 },
  { name:'Diabetes',     value:24 },
  { name:'Heart Disease',value:18 },
  { name:'COPD',         value:12 },
  { name:'Other',        value:14 },
]
const PIE_COLORS = ['#3b82f6','#06b6d4','#ef4444','#f59e0b','#8b5cf6']

const alertData = [
  { day:'Mon', critical:3, warning:8 }, { day:'Tue', critical:5, warning:12 },
  { day:'Wed', critical:2, warning:6 }, { day:'Thu', critical:7, warning:15 },
  { day:'Fri', critical:4, warning:9 }, { day:'Sat', critical:1, warning:4 },
  { day:'Sun', critical:2, warning:5 },
]

const TOOLTIP_STYLE = { contentStyle:{ background:'var(--cl-surface-2)', border:'1px solid var(--cl-border)', borderRadius:8, color:'#e2e8f0', fontSize:12 } }

export default function AdminReports() {
  return (
    <div className="cl-layout">
      <Sidebar />
      <div className="cl-main">
        <Navbar title="Admin Reports" />
        <div className="cl-page">
          <div className="cl-page-header" style={{ display:'flex', alignItems:'center', justifyContent:'space-between', flexWrap:'wrap', gap:'1rem' }}>
            <div>
              <h1 style={{ fontSize:'1.75rem' }}>📊 Platform Reports</h1>
              <p>Analytics generated by Lambda → S3 report pipeline</p>
            </div>
            <div style={{ display:'flex', gap:'0.75rem' }}>
              <button className="cl-btn cl-btn-secondary cl-btn-sm">⬇ Export PDF</button>
              <button className="cl-btn cl-btn-primary cl-btn-sm">🔄 Refresh</button>
            </div>
          </div>

          {/* Summary cards */}
          <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(180px, 1fr))', gap:'1rem', marginBottom:'2rem' }}>
            {[
              ['📈','Avg Daily Appointments','20.4','+8%','var(--cl-primary)'],
              ['👥','New Patients (Aug)','96','+15%','var(--cl-teal)'],
              ['🚨','Alert Resolution Rate','94.2%','+2.1%','var(--cl-green)'],
              ['📹','Teleconsults (Aug)','183','+23%','var(--cl-purple)'],
            ].map(([icon,label,value,change,color]) => (
              <div key={label} className="cl-stat-card">
                <div className="accent-bar" style={{ background:`linear-gradient(90deg, ${color}, transparent)` }} />
                <div style={{ fontSize:'1.5rem', marginBottom:'0.5rem' }}>{icon}</div>
                <div className="stat-value" style={{ fontSize:'1.5rem' }}>{value}</div>
                <div className="stat-label">{label}</div>
                <div style={{ fontSize:'0.72rem', color:'var(--cl-green)', fontWeight:700, marginTop:'0.25rem' }}>{change}</div>
              </div>
            ))}
          </div>

          {/* Charts row 1 */}
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1.5rem', marginBottom:'1.5rem' }}>
            <div className="cl-card">
              <h4 style={{ marginBottom:'1rem' }}>📅 Monthly Appointments</h4>
              <ResponsiveContainer width="100%" height={220}>
                <BarChart data={appointmentData} {...TOOLTIP_STYLE}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                  <XAxis dataKey="month" tick={{ fill:'#64748b', fontSize:11 }} tickLine={false} />
                  <YAxis tick={{ fill:'#64748b', fontSize:11 }} tickLine={false} axisLine={false} />
                  <Tooltip {...TOOLTIP_STYLE} />
                  <Bar dataKey="count" fill="#3b82f6" radius={[4,4,0,0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
            <div className="cl-card">
              <h4 style={{ marginBottom:'1rem' }}>👥 New Patient Registrations</h4>
              <ResponsiveContainer width="100%" height={220}>
                <LineChart data={patientData} {...TOOLTIP_STYLE}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                  <XAxis dataKey="month" tick={{ fill:'#64748b', fontSize:11 }} tickLine={false} />
                  <YAxis tick={{ fill:'#64748b', fontSize:11 }} tickLine={false} axisLine={false} />
                  <Tooltip {...TOOLTIP_STYLE} />
                  <Line type="monotone" dataKey="new" stroke="#06b6d4" strokeWidth={2.5} dot={{ fill:'#06b6d4', r:4 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Charts row 2 */}
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1.5rem' }}>
            <div className="cl-card">
              <h4 style={{ marginBottom:'1rem' }}>🏥 Patient Conditions Distribution</h4>
              <ResponsiveContainer width="100%" height={240}>
                <PieChart>
                  <Pie data={conditionDist} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,percent}) => `${name} ${(percent*100).toFixed(0)}%`} labelLine={{ stroke:'#64748b' }}>
                    {conditionDist.map((_, i) => <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />)}
                  </Pie>
                  <Tooltip {...TOOLTIP_STYLE} />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="cl-card">
              <h4 style={{ marginBottom:'1rem' }}>🚨 Weekly Alert Volume</h4>
              <ResponsiveContainer width="100%" height={240}>
                <BarChart data={alertData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                  <XAxis dataKey="day" tick={{ fill:'#64748b', fontSize:11 }} tickLine={false} />
                  <YAxis tick={{ fill:'#64748b', fontSize:11 }} tickLine={false} axisLine={false} />
                  <Tooltip {...TOOLTIP_STYLE} />
                  <Legend wrapperStyle={{ fontSize:11, color:'#64748b' }} />
                  <Bar dataKey="critical" fill="#ef4444" radius={[4,4,0,0]} />
                  <Bar dataKey="warning"  fill="#f59e0b" radius={[4,4,0,0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

        </div>
        <Footer />
      </div>
    </div>
  )
}
